---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:shitalkumardh/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACDR6e7Qug2z9AUd2oXWH4E/j5eRX+1P2myAdr3KUY6ZVAAAAKDCeXddwnl3
XQAAAAtzc2gtZWQyNTUxOQAAACDR6e7Qug2z9AUd2oXWH4E/j5eRX+1P2myAdr3KUY6ZVA
AAAEC1pGJwwIwps9TDlmd6baYtA37llqLzGrr8biXrBYH8ldHp7tC6DbP0BR3ahdYfgT+P
l5Ff7U/abIB2vcpRjplUAAAAHXNhbV9kQGNzLTg2Nzk3ODQ1Nzc0MC1kZWZhdWx0
    *****************************
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

